language: java
sudo: required
dist: trusty
jdk:
  - openjdk8
  - openjdk11
  - openjdk16
git:
  submodules: false
before_install:
  #- sudo apt-get update
  # workaround for missing cacerts in openjdk
  - sudo dpkg --purge --force-depends ca-certificates-java
  - sudo apt-get install ca-certificates-java
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
cache:
  directories:
    - '$HOME/.m2/repository'
