/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

dependencies {
    api(project(":acf-bukkit"))
    api(project(":acf-brigadier"))
    compileOnly("io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT")
    compileOnly("io.papermc.paper:paper-mojangapi:1.17-R0.1-SNAPSHOT")
    compileOnly(project(":acf-adventure-paper"))
}

description = "ACF (Paper)"
